#!/bin/sh
set -eu

BASE_DIR="${VENUS_RATHOLE_BASE_DIR:-/data/venus-rathole}"
CONFIG_FILE="$BASE_DIR/client.toml"
SERVICE_NAME="venus-rathole"

die() {
    printf '%s\n' "Error: $*" >&2
    exit 1
}

prompt() {
    label="$1"
    default="$2"
    value=""
    printf '%s [%s]: ' "$label" "$default" >&2
    IFS= read -r value || true
    if [ -z "$value" ]; then
        value="$default"
    fi
    printf '%s' "$value"
}

toml_value() {
    printf '%s' "$1" | sed 's/[\\"]/\\&/g'
}

generate_token() {
    [ -r /dev/urandom ] || die "/dev/urandom is required to generate a token"
    token=$(od -An -N 32 -tx1 /dev/urandom | tr -d ' \n')
    [ "${#token}" -eq 64 ] || die "could not generate a secure token"
    printf '%s' "$token"
}

valid_service_name() {
    case "$1" in
        *[!A-Za-z0-9_-]*|'') return 1 ;;
        *) return 0 ;;
    esac
}

restart_service() {
    if command -v sv >/dev/null 2>&1 && [ -d "/service/$SERVICE_NAME" ]; then
        sv restart "/service/$SERVICE_NAME" >/dev/null 2>&1 || true
    fi
}

[ -d "$BASE_DIR" ] || die "$BASE_DIR is not installed; run install.sh first"

default_remote="tunnel.example.com:2333"
default_name="gx-device-01"
existing_token=""
default_local="127.0.0.1:22"

if [ -f "$CONFIG_FILE" ]; then
    default_remote=$(sed -n 's/^remote_addr = "\(.*\)"$/\1/p' "$CONFIG_FILE" | head -n 1 || true)
    default_name=$(sed -n 's/^\[client\.services\.\([^]]*\)\]$/\1/p' "$CONFIG_FILE" | head -n 1 || true)
    existing_token=$(sed -n 's/^token = "\(.*\)"$/\1/p' "$CONFIG_FILE" | head -n 1 || true)
    default_local=$(sed -n 's/^local_addr = "\(.*\)"$/\1/p' "$CONFIG_FILE" | head -n 1 || true)
fi

remote_addr=$(prompt "Rathole server address" "$default_remote")
while :; do
    service_name=$(prompt "Unique device service name" "$default_name")
    if valid_service_name "$service_name"; then
        break
    fi
    printf '%s\n' "Use only letters, numbers, _ and -." >&2
done
if [ -n "$existing_token" ]; then
    printf '%s' "Service token [leave blank to keep current]: " >&2
else
    printf '%s' "Service token [press Enter to generate]: " >&2
fi
token=""
IFS= read -r token || true
if [ -z "$token" ]; then
    token="$existing_token"
fi
generated_token=0
if [ -z "$token" ]; then
    token=$(generate_token)
    generated_token=1
fi
local_addr=$(prompt "Local target address" "$default_local")

[ -n "$remote_addr" ] || die "server address cannot be empty"
[ -n "$token" ] || die "service token cannot be empty"
[ -n "$local_addr" ] || die "local target address cannot be empty"

umask 077
temporary="$CONFIG_FILE.tmp"
cat > "$temporary" <<EOF
# Generated by venus-rathole-client. Do not share this file: it contains a token.
[client]
remote_addr = "$(toml_value "$remote_addr")"

[client.services.$service_name]
token = "$(toml_value "$token")"
local_addr = "$(toml_value "$local_addr")"
EOF
mv "$temporary" "$CONFIG_FILE"

restart_service
printf '%s\n' "Saved $CONFIG_FILE and restarted $SERVICE_NAME."
if [ "$generated_token" -eq 1 ]; then
    printf '%s\n' ""
    printf '%s\n' "Generated device token. Add this exact value to the matching server service:"
    printf '%s\n' "$token"
fi
